# Generated by Django 3.1.2 on 2021-01-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDB',
            fields=[
                ('employeeID', models.AutoField(primary_key=True, serialize=False)),
                ('eName', models.CharField(max_length=255)),
                ('eLastName', models.CharField(max_length=255, null=True)),
                ('eMobNo', models.CharField(max_length=12)),
                ('eEmail', models.CharField(max_length=255)),
                ('eAddress', models.CharField(max_length=255)),
                ('eGroup', models.CharField(max_length=255, null=True)),
                ('eExtraInfo', models.CharField(max_length=255, null=True)),
                ('eDateOfRenewable', models.DateField(null=True)),
            ],
        ),
    ]
