# Generated by Django 3.1.2 on 2021-01-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedb',
            name='eMobNo',
            field=models.PositiveIntegerField(),
        ),
    ]
